"""
utils/report_saver.py
──────────────────────
Saves the final report to the specified local folder.
Produces two files:
  - report_<domain>_<timestamp>.md   (markdown)
  - report_<domain>_<timestamp>.html (styled HTML for easy reading)
"""

import os
import re
from datetime import datetime
from pathlib import Path


# ── HTML wrapper template ─────────────────────────────────────────
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Source+Serif+4:ital,wght@0,300;0,400;0,600;1,400&display=swap');

    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}

    body {{
      background: #0e0e18;
      color: #dcdcec;
      font-family: 'Source Serif 4', Georgia, serif;
      font-size: 18px;
      line-height: 1.75;
      padding: 3rem 1.5rem;
    }}

    .container {{
      max-width: 760px;
      margin: 0 auto;
    }}

    .meta {{
      font-size: 13px;
      color: #666680;
      margin-bottom: 2.5rem;
      letter-spacing: 0.05em;
      text-transform: uppercase;
    }}

    h1, h2, h3 {{
      font-family: 'Playfair Display', Georgia, serif;
      color: #f0f0fc;
      line-height: 1.25;
    }}

    h1 {{ font-size: 2.4rem; margin-bottom: 0.5rem; }}
    h2 {{ font-size: 1.5rem; margin: 2.5rem 0 0.8rem; border-bottom: 1px solid #1e1e30; padding-bottom: 0.4rem; }}
    h3 {{ font-size: 1.2rem; margin: 1.5rem 0 0.5rem; }}

    p {{ margin-bottom: 1.2rem; }}

    ul, ol {{
      margin: 0 0 1.2rem 1.5rem;
    }}

    li {{ margin-bottom: 0.4rem; }}

    strong {{ color: #f5b800; font-weight: 600; }}
    em {{ font-style: italic; color: #b0b0cc; }}

    blockquote {{
      border-left: 3px solid #f5b800;
      padding: 0.5rem 0 0.5rem 1.2rem;
      margin: 1.5rem 0;
      color: #a0a0c0;
      font-style: italic;
    }}

    code {{
      background: #1a1a2e;
      padding: 0.15em 0.4em;
      border-radius: 3px;
      font-family: 'JetBrains Mono', monospace;
      font-size: 0.85em;
      color: #f5b800;
    }}

    hr {{
      border: none;
      border-top: 1px solid #1e1e30;
      margin: 2rem 0;
    }}

    .footer {{
      margin-top: 4rem;
      padding-top: 1.5rem;
      border-top: 1px solid #1e1e30;
      font-size: 12px;
      color: #444460;
      text-align: center;
    }}
  </style>
</head>
<body>
  <div class="container">
    <div class="meta">Research Pulse · {domain} · {timestamp}</div>
    {body}
    <div class="footer">Generated by Research Pulse · {timestamp}</div>
  </div>
</body>
</html>"""


def _md_to_html_body(markdown_text: str) -> str:
    """Convert markdown to HTML body content."""
    try:
        import markdown2
        return markdown2.markdown(
            markdown_text,
            extras=["fenced-code-blocks", "tables", "header-ids", "strike"],
        )
    except ImportError:
        # Very basic fallback if markdown2 isn't installed
        html = markdown_text
        html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
        html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
        html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
        html = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html)
        html = "\n".join(
            f"<p>{line}</p>" if line.strip() and not line.startswith("<") else line
            for line in html.splitlines()
        )
        return html


def save_report(
    report_markdown: str,
    domain: str,
    output_folder: str,
    research_data: dict | None = None,
) -> dict[str, str]:
    """
    Save the report to output_folder.

    Returns a dict with keys:
      md_path   — path to the markdown file
      html_path — path to the styled HTML file
    """
    # ── Prepare folder ────────────────────────────────────────────
    folder = Path(output_folder).expanduser().resolve()
    folder.mkdir(parents=True, exist_ok=True)

    # ── Build filename ─────────────────────────────────────────────
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_domain = re.sub(r"[^\w\-]", "_", domain.lower())[:40]
    base_name = f"report_{safe_domain}_{ts}"

    # ── Save markdown ─────────────────────────────────────────────
    md_path = folder / f"{base_name}.md"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(f"<!-- Research Pulse | {domain} | {datetime.now().isoformat()} -->\n\n")
        f.write(report_markdown)

    # ── Save HTML ─────────────────────────────────────────────────
    html_body = _md_to_html_body(report_markdown)
    title_match = re.search(r"^##?\s+(.+)$", report_markdown, re.MULTILINE)
    title = title_match.group(1) if title_match else f"Research Report: {domain}"

    html_content = HTML_TEMPLATE.format(
        title=title,
        domain=domain,
        timestamp=datetime.now().strftime("%B %d, %Y · %H:%M"),
        body=html_body,
    )

    html_path = folder / f"{base_name}.html"
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    return {
        "md_path":   str(md_path),
        "html_path": str(html_path),
        "folder":    str(folder),
        "base_name": base_name,
    }